### ISSUE TITLE
Getting TypeError: Cannot read property 'consumerKey' of undefined

### ISSUE THREAD

**Issue by todenvolkov** [RapidSoftwareSolutions/Marketplace-Twitter-Package#1]
I've tried all variants of headers, encodings, bodies.  ALways
Getting TypeError: Cannot read property 'consumerKey' of undefined

**Comment by Bukati** [comment]
Hi, Can you share your code snippet?

**Comment by todenvolkov** [comment]
It's your code whole without modifications (except port)

**Comment by Bukati** [comment]
Which one? NodeJS? PHP?

**Comment by todenvolkov** [comment]
nodejs

This is CURL example of request
`POST /api/Twitter/tweet HTTP/1.1
Host: localhost:8082
Content-Type: application/x-www-form-urlencoded
Cache-Control: no-cache
Postman-Token: a4191cee-6204-7763-9976-ef24ab0d3c9f

consumerKey=&accessTokenKey=-HC5tmXUhs9uAJCDB9JMjqmICThFVypG&consumerSecret=&accessTokenSecret=&tweetBody=Hello%2Bworld&to=`

This is what i see in console (i put console.log(req.body) at start, to check
`/**
 * Created by Gilad on 16/06/16.
 */

const Twitter = require('twitter');

module.exports.tweet = function (req, res) {
    var args = req.body.args;
    var project = req.body.projectMetadata;
    console.log(req.body);`

While NODE logs this

`UP
{ consumerKey: '88',
  accessTokenKey: '8-HC5tmXUhs9uAJCDB9JMjqmICThFVypG',
  consumerSecret: '8',
  accessTokenSecret: '8',
  tweetBody: 'Hello+world',
  to: '' }
TypeError: Cannot read property 'consumerKey' of undefined
    at module.exports.tweet (/Users/denisvolkov/Downloads/Marketplace-Twitter-Package-master/blocks/tweet.js:12:27)
    at Layer.handle [as handle_request] (/Users/denisvolkov/Downloads/Marketplace-Twitter-Package-master/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/denisvolkov/Downloads/Marketplace-Twitter-Package-master/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/denisvolkov/Downloads/Marketplace-Twitter-Package-master/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/denisvolkov/Downloads/Marketplace-Twitter-Package-master/node_modules/express/lib/router/layer.js:95:5)
    at /Users/denisvolkov/Downloads/Marketplace-Twitter-Package-master/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/Users/denisvolkov/Downloads/Marketplace-Twitter-Package-master/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/denisvolkov/Downloads/Marketplace-Twitter-Package-master/node_modules/express/lib/router/index.js:271:10)
    at /Users/denisvolkov/Downloads/Marketplace-Twitter-Package-master/node_modules/body-parser/lib/read.js:129:5
    at invokeCallback (/Users/denisvolkov/Downloads/Marketplace-Twitter-Package-master/node_modules/raw-body/index.js:262:16)
`

**Comment by Bukati** [comment]
Got your issue... 
You are trying to use this package locally.
RapidAPI packages are for our marketplace.

Go to http://www.rapidapi.com, after the registration you will get a code snippet which you should use.

For example:

```javascript

const RapidAPI = require('rapidapi-connect');
const rapid = new RapidAPI("GET_FROM_RAPIDAPI.COM", "GET_FROM_RAPIDAPI.COM");

rapid.call('Twitter', 'tweet', { 
	'consumerKey': 'XXXX',
	'consumerSecret': 'XXXXX',
	'accessTokenKey': 'XXXXX',
	'accessTokenSecret': 'XXXXXX',
	'tweetBody': 'Hello World'
 
}).on('success', (payload)=>{
	 /*YOUR CODE GOES HERE*/ 
}).on('error', (payload)=>{
	 /*YOUR CODE GOES HERE*/ 
});

```

**Comment by todenvolkov** [comment]
So all these modules are not working? Why do they stay here?

**Comment by Bukati** [comment]
They working, but they built for RapidAPI Marketplace. Think of it as plugins for a big system.

**Comment by todenvolkov** [comment]
I thought github aimed to be mostly for running and open code, but not for marketing :(
I see that code is correct and seems to be working...

**Comment by Bukati** [comment]
It is open code. As I said, think of it as plugins for a big system.
Packages used to simplify the way people work with APIs, it open source - every one can contribute, ask for features, share ideas, etc.
RapidAPI (http://rapidapi.com), is a marketplace and the engine which is required to run all those packages. It's free for use and will always be free.

**Comment by todenvolkov** [comment]
Thanks!
